// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// epanechnikov_kernel_cpp
NumericVector epanechnikov_kernel_cpp(const NumericVector& x);
RcppExport SEXP _CompStatPackage_epanechnikov_kernel_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(epanechnikov_kernel_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_kernel_cpp
NumericVector gaussian_kernel_cpp(NumericVector x);
RcppExport SEXP _CompStatPackage_gaussian_kernel_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_kernel_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// kernel_cpp_epanechnikov
List kernel_cpp_epanechnikov(const NumericVector& grid_points, const NumericVector& vec_obs, double bandwidth);
RcppExport SEXP _CompStatPackage_kernel_cpp_epanechnikov(SEXP grid_pointsSEXP, SEXP vec_obsSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type grid_points(grid_pointsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type vec_obs(vec_obsSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_cpp_epanechnikov(grid_points, vec_obs, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// kernel_cpp_gaussian
List kernel_cpp_gaussian(const NumericVector& grid_points, const NumericVector& vec_obs, double bandwidth);
RcppExport SEXP _CompStatPackage_kernel_cpp_gaussian(SEXP grid_pointsSEXP, SEXP vec_obsSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type grid_points(grid_pointsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type vec_obs(vec_obsSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_cpp_gaussian(grid_points, vec_obs, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// binning_cpp
NumericVector binning_cpp(const NumericVector& vec_obs, double lower, double upper, int number_of_bins);
RcppExport SEXP _CompStatPackage_binning_cpp(SEXP vec_obsSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP number_of_binsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type vec_obs(vec_obsSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_bins(number_of_binsSEXP);
    rcpp_result_gen = Rcpp::wrap(binning_cpp(vec_obs, lower, upper, number_of_bins));
    return rcpp_result_gen;
END_RCPP
}
// kernel_cpp_epanechnikov_binning
List kernel_cpp_epanechnikov_binning(const NumericVector& grid_points, const NumericVector& vec_obs, double bandwidth);
RcppExport SEXP _CompStatPackage_kernel_cpp_epanechnikov_binning(SEXP grid_pointsSEXP, SEXP vec_obsSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type grid_points(grid_pointsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type vec_obs(vec_obsSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_cpp_epanechnikov_binning(grid_points, vec_obs, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// kernel_cpp_gaussian_binning
List kernel_cpp_gaussian_binning(const NumericVector& grid_points, const NumericVector& vec_obs, double bandwidth);
RcppExport SEXP _CompStatPackage_kernel_cpp_gaussian_binning(SEXP grid_pointsSEXP, SEXP vec_obsSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type grid_points(grid_pointsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type vec_obs(vec_obsSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_cpp_gaussian_binning(grid_points, vec_obs, bandwidth));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CompStatPackage_epanechnikov_kernel_cpp", (DL_FUNC) &_CompStatPackage_epanechnikov_kernel_cpp, 1},
    {"_CompStatPackage_gaussian_kernel_cpp", (DL_FUNC) &_CompStatPackage_gaussian_kernel_cpp, 1},
    {"_CompStatPackage_kernel_cpp_epanechnikov", (DL_FUNC) &_CompStatPackage_kernel_cpp_epanechnikov, 3},
    {"_CompStatPackage_kernel_cpp_gaussian", (DL_FUNC) &_CompStatPackage_kernel_cpp_gaussian, 3},
    {"_CompStatPackage_binning_cpp", (DL_FUNC) &_CompStatPackage_binning_cpp, 4},
    {"_CompStatPackage_kernel_cpp_epanechnikov_binning", (DL_FUNC) &_CompStatPackage_kernel_cpp_epanechnikov_binning, 3},
    {"_CompStatPackage_kernel_cpp_gaussian_binning", (DL_FUNC) &_CompStatPackage_kernel_cpp_gaussian_binning, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_CompStatPackage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
