# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Perform EM (C++)
#'
#' Finds parameter estimate using EM.
#'
#' @param x Data.
#' @param listOfInitialPar List of initial parameters.
#' @param maxIteration Maximum iterations.
#' @param epsilon Stopping tolerance.
#' @return A list of estimated paramters.
perform_em_cpp <- function(x, listOfInitialPar, maxIteration, epsilon) {
    .Call('_CompStatPackage_perform_em_cpp', PACKAGE = 'CompStatPackage', x, listOfInitialPar, maxIteration, epsilon)
}

#' Epanechnikov Kernel Density Estimation (C++)
#'
#' Computes kernel density estimates at specified grid points using the Epanechnikov kernel.
#' The function is parallelized with OpenMP for improved performance.
#'
#' @param grid_points A numeric vector of grid points where density estimates are evaluated.
#' @param vec_obs A numeric vector of observed data points.
#' @param bandwidth A positive numeric value specifying the smoothing bandwidth.
#' @return A list with Grid points and density estimates.
kernel_cpp_epanechnikov <- function(grid_points, vec_obs, bandwidth) {
    .Call('_CompStatPackage_kernel_cpp_epanechnikov', PACKAGE = 'CompStatPackage', grid_points, vec_obs, bandwidth)
}

#' Gaussian Kernel Density Estimation (C++)
#'
#' Computes kernel density estimates at specified grid points using the Gaussian kernel.
#' The function is parallelized with OpenMP for optimized performance on large data sets.
#'
#' @param grid_points A numeric vector of grid points where density estimates are evaluated.
#' @param vec_obs A numeric vector of observed data points.
#' @param bandwidth A positive numeric value specifying the smoothing bandwidth.
#' @return A list with Grid points and density estimates.
kernel_cpp_gaussian <- function(grid_points, vec_obs, bandwidth) {
    .Call('_CompStatPackage_kernel_cpp_gaussian', PACKAGE = 'CompStatPackage', grid_points, vec_obs, bandwidth)
}

#' Epanechnikov Kernel Density Estimation with Binning (C++)
#'
#' Computes kernel density estimates at specified grid points using the Epanechnikov kernel
#' with a binning approach for improved performance.
#'
#' @param grid_points A numeric vector of grid points where density estimates are evaluated.
#' @param vec_obs A numeric vector of observed data points.
#' @param bandwidth A positive numeric value specifying the smoothing bandwidth.
#' @return A list with Grid points and density estimates.
kernel_cpp_epanechnikov_binning <- function(grid_points, vec_obs, bandwidth) {
    .Call('_CompStatPackage_kernel_cpp_epanechnikov_binning', PACKAGE = 'CompStatPackage', grid_points, vec_obs, bandwidth)
}

#' Gaussian Kernel Density Estimation with Binning (C++)
#'
#' Computes kernel density estimates at specified grid points using the Gaussian kernel
#' with a binning approach for improved performance.
#'
#' @param grid_points A numeric vector of grid points where density estimates are evaluated.
#' @param vec_obs A numeric vector of observed data points.
#' @param bandwidth A positive numeric value specifying the smoothing bandwidth.
#' @return A list with Grid points and density estimates.
kernel_cpp_gaussian_binning <- function(grid_points, vec_obs, bandwidth) {
    .Call('_CompStatPackage_kernel_cpp_gaussian_binning', PACKAGE = 'CompStatPackage', grid_points, vec_obs, bandwidth)
}

#' Set Data Vectors (C++)
#'
#' Initializes the global vectors `x` and `z` with input values from R.
#' @param x_in A numeric vector to set the global vector `x`.
#' @param z_in A numeric vector to set the global vector `z`.
#' @return None. This function is used for its side effects.
set_data_vectors <- function(x_in, z_in) {
    invisible(.Call('_CompStatPackage_set_data_vectors', PACKAGE = 'CompStatPackage', x_in, z_in))
}

#' Log Target Density for Vector of Observations (C++)
#'
#' Calculates the log target density for each value in a numeric vector.
#'
#' @param y A numeric vector of values for which to calculate the log target density.
#' @return A numeric vector of log target density values.
log_target_density_cpp <- function(y) {
    .Call('_CompStatPackage_log_target_density_cpp', PACKAGE = 'CompStatPackage', y)
}

#' Derivative of Log Target Density for Vector of Observations (C++)
#'
#' Calculates the derivative of the log target density for each value in a numeric vector.
#'
#' @param y A numeric vector of values for which to calculate the derivative of the log target density.
#' @return A numeric vector of derivative values of the log target density.
d_log_target_density_cpp <- function(y) {
    .Call('_CompStatPackage_d_log_target_density_cpp', PACKAGE = 'CompStatPackage', y)
}

#' Gaussian Rejection Sampler Accept/Reject Decisions (C++)
#'
#' Determines acceptance of samples in a Gaussian rejection sampling algorithm.
#'
#' @param mu Mean of the Gaussian distribution.
#' @param sd Standard deviation of the Gaussian distribution.
#' @param log_alpha_prime Log scaling parameter for acceptance region.
#' @param proposals A numeric vector of proposed sample values.
#' @param u_samples A numeric vector of random uniform values for rejection sampling.
#' @return A logical vector indicating accepted (\code{TRUE}) or rejected (\code{FALSE}) samples.
get_accepts_gaussian_cpp <- function(mu, sd, log_alpha_prime, proposals, u_samples) {
    .Call('_CompStatPackage_get_accepts_gaussian_cpp', PACKAGE = 'CompStatPackage', mu, sd, log_alpha_prime, proposals, u_samples)
}

#' Sampler Function with Acceptance-Rejection (C++)
#'
#' Samples values according to a custom acceptance-rejection method.
#'
#' @param n Integer specifying the number of samples.
#' @param c Constant multiplier for scaling.
#' @param Q A cumulative probability distribution vector.
#' @param a A vector of coefficients.
#' @param b A vector of coefficients.
#' @param z A vector of control parameters.
#' @return A numeric vector of sampled values.
create_sampler_function_cpp <- function(n, c, Q, a, b, z) {
    .Call('_CompStatPackage_create_sampler_function_cpp', PACKAGE = 'CompStatPackage', n, c, Q, a, b, z)
}

#' Log Envelope Density Calculation (C++)
#'
#' Calculates a piecewise linear log envelope density using input parameters.
#'
#' @param x A numeric vector of values for which to calculate the envelope density.
#' @param z A numeric vector for interval boundaries.
#' @param a A numeric vector of coefficients.
#' @param b A numeric vector of coefficients.
#' @return A numeric vector of log envelope density values.
create_log_envelope_density_cpp <- function(x, z, a, b) {
    .Call('_CompStatPackage_create_log_envelope_density_cpp', PACKAGE = 'CompStatPackage', x, z, a, b)
}

