# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Epanechnikov Kernel Function (C++)
#'
#' Calculates the Epanechnikov kernel for a given vector of input values.
#'
#' @param x A numeric vector of values for which to calculate the Epanechnikov kernel.
#' @return A numeric vector of kernel values, with zeros for inputs outside the range -1, 1.
#' @export
epanechnikov_kernel_cpp <- function(x) {
    .Call('_CompStatPackage_epanechnikov_kernel_cpp', PACKAGE = 'CompStatPackage', x)
}

#' Gaussian Kernel Function (C++)
#'
#' Calculates the Gaussian (Normal) kernel for a given vector of input values.
#'
#' @param x A numeric vector of values for which to calculate the Gaussian kernel.
#' @return A numeric vector of Gaussian kernel values for each element in `x`.
#' @export
gaussian_kernel_cpp <- function(x) {
    .Call('_CompStatPackage_gaussian_kernel_cpp', PACKAGE = 'CompStatPackage', x)
}

#' Epanechnikov Kernel Density Estimation (C++)
#'
#' Computes kernel density estimates at specified grid points using the Epanechnikov kernel.
#' The function is parallelized with OpenMP for improved performance.
#'
#' @param grid_points A numeric vector of grid points where density estimates are evaluated.
#' @param vec_obs A numeric vector of observed data points.
#' @param bandwidth A positive numeric value specifying the smoothing bandwidth.
#' @return A list with two components:
#'   - `x`: Grid points where the density is estimated.
#'   - `y`: Corresponding density estimates using the Epanechnikov kernel.
#' @export
kernel_cpp_epanechnikov <- function(grid_points, vec_obs, bandwidth) {
    .Call('_CompStatPackage_kernel_cpp_epanechnikov', PACKAGE = 'CompStatPackage', grid_points, vec_obs, bandwidth)
}

#' Gaussian Kernel Density Estimation (C++)
#'
#' Computes kernel density estimates at specified grid points using the Gaussian kernel.
#' The function is parallelized with OpenMP for optimized performance on large data sets.
#'
#' @param grid_points A numeric vector of grid points where density estimates are evaluated.
#' @param vec_obs A numeric vector of observed data points.
#' @param bandwidth A positive numeric value specifying the smoothing bandwidth.
#' @return A list with two components:
#'   - `x`: Grid points where the density is estimated.
#'   - `y`: Corresponding density estimates using the Gaussian kernel.
#' @export
kernel_cpp_gaussian <- function(grid_points, vec_obs, bandwidth) {
    .Call('_CompStatPackage_kernel_cpp_gaussian', PACKAGE = 'CompStatPackage', grid_points, vec_obs, bandwidth)
}

#' Data Binning Function (C++)
#'
#' Bins observed data points within a specified range, dividing the range into equal-width bins.
#'
#' @param vec_obs A numeric vector of observed data points.
#' @param lower The lower bound of the binning range.
#' @param upper The upper bound of the binning range.
#' @param number_of_bins An integer specifying the number of bins.
#' @return A numeric vector with counts of observations in each bin.
#' @export
binning_cpp <- function(vec_obs, lower, upper, number_of_bins) {
    .Call('_CompStatPackage_binning_cpp', PACKAGE = 'CompStatPackage', vec_obs, lower, upper, number_of_bins)
}

#' Epanechnikov Kernel Density Estimation with Binning (C++)
#'
#' Computes kernel density estimates at specified grid points using the Epanechnikov kernel
#' with a binning approach for improved performance.
#'
#' @param grid_points A numeric vector of grid points where density estimates are evaluated.
#' @param vec_obs A numeric vector of observed data points.
#' @param bandwidth A positive numeric value specifying the smoothing bandwidth.
#' @return A list with two components:
#'   - `x`: Grid points where the density is estimated.
#'   - `y`: Corresponding density estimates using the Epanechnikov kernel and binning.
#' @export
kernel_cpp_epanechnikov_binning <- function(grid_points, vec_obs, bandwidth) {
    .Call('_CompStatPackage_kernel_cpp_epanechnikov_binning', PACKAGE = 'CompStatPackage', grid_points, vec_obs, bandwidth)
}

#' Gaussian Kernel Density Estimation with Binning (C++)
#'
#' Computes kernel density estimates at specified grid points using the Gaussian kernel
#' with a binning approach for improved performance.
#'
#' @param grid_points A numeric vector of grid points where density estimates are evaluated.
#' @param vec_obs A numeric vector of observed data points.
#' @param bandwidth A positive numeric value specifying the smoothing bandwidth.
#' @return A list with two components:
#'   - `x`: Grid points where the density is estimated.
#'   - `y`: Corresponding density estimates using the Gaussian kernel and binning.
#' @export
kernel_cpp_gaussian_binning <- function(grid_points, vec_obs, bandwidth) {
    .Call('_CompStatPackage_kernel_cpp_gaussian_binning', PACKAGE = 'CompStatPackage', grid_points, vec_obs, bandwidth)
}

#' @name set_data_vectors
NULL

#' @name log_target_density_single_obs
NULL

#' @name log_target_density_cpp
NULL

#' @name d_log_target_density_single_obs
NULL

#' @name d_log_target_density_cpp
NULL

#' @name log_envelope_gaussian_density
NULL

#' @name get_accepts_gaussian_cpp
NULL

#' @name create_sampler_function_cpp
NULL

#' @name create_log_envelope_density_cpp
NULL

set_data_vectors <- function(x_in, z_in) {
    invisible(.Call('_CompStatPackage_set_data_vectors', PACKAGE = 'CompStatPackage', x_in, z_in))
}

log_target_density_cpp <- function(y) {
    .Call('_CompStatPackage_log_target_density_cpp', PACKAGE = 'CompStatPackage', y)
}

d_log_target_density_cpp <- function(y) {
    .Call('_CompStatPackage_d_log_target_density_cpp', PACKAGE = 'CompStatPackage', y)
}

get_accepts_gaussian_cpp <- function(mu, sd, log_alpha_prime, proposals, u_samples) {
    .Call('_CompStatPackage_get_accepts_gaussian_cpp', PACKAGE = 'CompStatPackage', mu, sd, log_alpha_prime, proposals, u_samples)
}

create_sampler_function_cpp <- function(n, c, Q, a, b, z) {
    .Call('_CompStatPackage_create_sampler_function_cpp', PACKAGE = 'CompStatPackage', n, c, Q, a, b, z)
}

create_log_envelope_density_cpp <- function(x, z, a, b) {
    .Call('_CompStatPackage_create_log_envelope_density_cpp', PACKAGE = 'CompStatPackage', x, z, a, b)
}

