# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Epanechnikov Kernel Function (C++)
#'
#' Calculates the Epanechnikov kernel for a given vector of input values.
#'
#' @param x A numeric vector of values for which to calculate the Epanechnikov kernel.
#' @return A numeric vector of kernel values, with zeros for inputs outside the range -1, 1.
#' @export
epanechnikov_kernel_cpp <- function(x) {
    .Call('_CompStatPackage_epanechnikov_kernel_cpp', PACKAGE = 'CompStatPackage', x)
}

#' Gaussian Kernel Function (C++)
#'
#' Calculates the Gaussian (Normal) kernel for a given vector of input values.
#'
#' @param x A numeric vector of values for which to calculate the Gaussian kernel.
#' @return A numeric vector of Gaussian kernel values for each element in `x`.
#' @export
gaussian_kernel_cpp <- function(x) {
    .Call('_CompStatPackage_gaussian_kernel_cpp', PACKAGE = 'CompStatPackage', x)
}

#' Epanechnikov Kernel Density Estimation (C++)
#'
#' Computes kernel density estimates at specified grid points using the Epanechnikov kernel.
#' The function is parallelized with OpenMP for improved performance.
#'
#' @param grid_points A numeric vector of grid points where density estimates are evaluated.
#' @param vec_obs A numeric vector of observed data points.
#' @param bandwidth A positive numeric value specifying the smoothing bandwidth.
#' @return A list with two components:
#'   - `x`: Grid points where the density is estimated.
#'   - `y`: Corresponding density estimates using the Epanechnikov kernel.
#' @export
kernel_cpp_epanechnikov <- function(grid_points, vec_obs, bandwidth) {
    .Call('_CompStatPackage_kernel_cpp_epanechnikov', PACKAGE = 'CompStatPackage', grid_points, vec_obs, bandwidth)
}

#' Gaussian Kernel Density Estimation (C++)
#'
#' Computes kernel density estimates at specified grid points using the Gaussian kernel.
#' The function is parallelized with OpenMP for optimized performance on large data sets.
#'
#' @param grid_points A numeric vector of grid points where density estimates are evaluated.
#' @param vec_obs A numeric vector of observed data points.
#' @param bandwidth A positive numeric value specifying the smoothing bandwidth.
#' @return A list with two components:
#'   - `x`: Grid points where the density is estimated.
#'   - `y`: Corresponding density estimates using the Gaussian kernel.
#' @export
kernel_cpp_gaussian <- function(grid_points, vec_obs, bandwidth) {
    .Call('_CompStatPackage_kernel_cpp_gaussian', PACKAGE = 'CompStatPackage', grid_points, vec_obs, bandwidth)
}

#' Data Binning Function (C++)
#'
#' Bins observed data points within a specified range, dividing the range into equal-width bins.
#'
#' @param vec_obs A numeric vector of observed data points.
#' @param lower The lower bound of the binning range.
#' @param upper The upper bound of the binning range.
#' @param number_of_bins An integer specifying the number of bins.
#' @return A numeric vector with counts of observations in each bin.
#' @export
binning_cpp <- function(vec_obs, lower, upper, number_of_bins) {
    .Call('_CompStatPackage_binning_cpp', PACKAGE = 'CompStatPackage', vec_obs, lower, upper, number_of_bins)
}

#' Epanechnikov Kernel Density Estimation with Binning (C++)
#'
#' Computes kernel density estimates at specified grid points using the Epanechnikov kernel
#' with a binning approach for improved performance.
#'
#' @param grid_points A numeric vector of grid points where density estimates are evaluated.
#' @param vec_obs A numeric vector of observed data points.
#' @param bandwidth A positive numeric value specifying the smoothing bandwidth.
#' @return A list with two components:
#'   - `x`: Grid points where the density is estimated.
#'   - `y`: Corresponding density estimates using the Epanechnikov kernel and binning.
#' @export
kernel_cpp_epanechnikov_binning <- function(grid_points, vec_obs, bandwidth) {
    .Call('_CompStatPackage_kernel_cpp_epanechnikov_binning', PACKAGE = 'CompStatPackage', grid_points, vec_obs, bandwidth)
}

#' Gaussian Kernel Density Estimation with Binning (C++)
#'
#' Computes kernel density estimates at specified grid points using the Gaussian kernel
#' with a binning approach for improved performance.
#'
#' @param grid_points A numeric vector of grid points where density estimates are evaluated.
#' @param vec_obs A numeric vector of observed data points.
#' @param bandwidth A positive numeric value specifying the smoothing bandwidth.
#' @return A list with two components:
#'   - `x`: Grid points where the density is estimated.
#'   - `y`: Corresponding density estimates using the Gaussian kernel and binning.
#' @export
kernel_cpp_gaussian_binning <- function(grid_points, vec_obs, bandwidth) {
    .Call('_CompStatPackage_kernel_cpp_gaussian_binning', PACKAGE = 'CompStatPackage', grid_points, vec_obs, bandwidth)
}

